config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources :create_opportunities

  get '/api/send_text', to: 'api#send_text'

  get 'discoveroppotunites', to: 'discover_opportunities#search', as: 'search_opportunities'

  get 'discoveroppotunites/:id', to: 'discover_opportunities#show', as: 'show_opportunity'

  get 'discoveropportunities/:id/edit', to: 'discover_opportunities#edit', as: 'edit_opportunity'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/create_opportunity.rb
# frozen_string_literal: true

class CreateOpportunity < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :email, presence: true
  validates :organization_name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  validates :phone, presence: true
  validates :user_type, presence: true

  has_many :create_opportunities

  def organization?
    user_type == 'organization'
  end

  def volunteer?
    user_type == 'volunteer'
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def send_text
    opportunity = CreateOpportunity.find(params[:opportunity_id])
    user_phone_number = opportunity.user.phone

    user_message = Twilio::REST::Client.new.messages.create(
      from: '+18886819261',
      body: "Thanks for expressing interest in #{opportunity.title}. Will reach out to you soon!",
      to: user_phone_number
    )
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[first_name last_name phone opt_to_text email user_type])
  end
end

app/controllers/create_opportunities_controller.rb
# frozen_string_literal: true

class CreateOpportunitiesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :require_organization, only: [:new]

  def index
    @create_opportunity = CreateOpportunity.all
  end

  def new
    @create_opportunity = CreateOpportunity.new
  end

  def show
    @create_opportunity = CreateOpportunity.find(params[:id])
  end

  def create
    @create_opportunity = current_user.create_opportunities.build(create_opportunity_params)

    respond_to do |format|
      if @create_opportunity.save
        format.html { redirect_to search_opportunities_path, notice: 'Opportunity was successfully created.' }
        format.json { render :show, status: :created, location: @create_opportunity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @create_opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @create_opportunity = CreateOpportunity.find(params[:id])

    if @create_opportunity.update(create_opportunity_params)
      redirect_to search_opportunities_path, notice: 'Opportunity was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @create_opportunity = CreateOpportunity.find(params[:id])
    @create_opportunity.destroy

    redirect_to search_opportunities_path, notice: 'Opportunity was successfully deleted.'
  end

  private

  def create_opportunity_params
    params.require(:create_opportunity).permit(:title, :description, :organization_name, :email, :location, :date,
                                               :time)
  end

  def require_organization
    return if current_user.organization?

    flash[:alert] = 'You do not have permission to access this page.'
    redirect_to root_path
  end
end

app/controllers/discover_opportunities_controller.rb
# frozen_string_literal: true

class DiscoverOpportunitiesController < ApplicationController
  def search
    @opportunities = if params[:search]
                       CreateOpportunity.where('title ILIKE ? OR location ILIKE ?', "%#{params[:search]}%",
                                               "%#{params[:search]}%").distinct
                     else
                       CreateOpportunity.all
                     end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @create_opportunity = CreateOpportunity.find(params[:id])
  end

  def edit
    @create_opportunity = CreateOpportunity.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/create_opportunities_helper.rb
# frozen_string_literal: true

module CreateOpportunitiesHelper
end

app/helpers/discover_opportunities_helper.rb
# frozen_string_literal: true

module DiscoverOpportunitiesHelper
end

app/helpers/discoveropportunities_helper.rb
# frozen_string_literal: true

module DiscoveropportunitiesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

module RolesHelper
end

app/views/create_opportunities/_form.html.erb
<div class="organazation-form">
<%= form_with(model: @create_opportunity) do |form| %>
   
    <h1 class="organization-form-title">Create Opportunities</h1>
    <p class="organization-form-description">Inspire collaboration, drive impactful change, and create purposeful engagements that empower individuals for lasting societal impact.</p>

    <div class="form-group">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control', placeholder: "Enter title" %>
    </div>
    
    <div class="form-group">
        <%= form.label :description, class: 'form-label' %>
        <%= form.text_area :description, class: 'form-control', placeholder: "Enter description" %>
    </div>
    

    <div class="form-group">
        <%= form.label :organization_name, class: 'form-label' %>
        <%= form.text_field :organization_name, class: 'form-control', placeholder: "Enter organization name" %>
    </div>
    
    <div class="form-group">
        <%= form.label :location, class: 'form-label' %>
        <%= form.text_field :location, class: 'form-control', placeholder: "Enter location" %>
    </div>
    
    <div class="form-group create-email">
        <%= form.label :email, class: 'form-label' %>
        <%= form.email_field :email, class: 'form-control', placeholder: "Enter email" %>
    </div>
    
    <div class="form-group">
        <%= form.label :date, class: 'form-label' %>
        <%= form.date_field :date, class: 'form-control'%>
    </div>
    
    <div class="form-group">
        <%= form.label :time, class: 'form-label' %>
        <%= form.time_field :time, class: 'form-control'%>
    </div>
      
    <div class="form-group submit-button">
          <%= form.submit "Create Opportunity" %>
    </div>
 
      <% end %>

</div>

app/views/create_opportunities/new.html.erb
<%= render "form", create_opportunity: @create_opportunity %>

app/views/discover_opportunities/_form.html.erb
<%= form_with(model: @create_opportunity) do |form| %>
    <div class="form-container">
      
      <div class="form-group">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control', placeholder: "Enter title", value: @create_opportunity.title %>
      </div>
      
      <div class="form-group">
        <%= form.label :description, class: 'form-label' %>
        <%= form.text_area :description, class: 'form-control', placeholder: "Enter description", value: @create_opportunity.description %>
      </div>
  
      <div class="form-group">
        <%= form.label :organization_name, class: 'form-label' %>
        <%= form.text_field :organization_name, class: 'form-control', placeholder: "Enter organization name", value: @create_opportunity.organization_name %>
      </div>
      
      <div class="form-group">
        <%= form.label :location, class: 'form-label' %>
        <%= form.text_field :location, class: 'form-control', placeholder: "Enter location", value: @create_opportunity.location %>
      </div>
  
      <div class="form-group">
        <%= form.submit "Update Opportunity", class: 'btn btn-primary' %>
      </div>
      
    </div>
  <% end %>
  

app/views/discover_opportunities/_search_results.html.erb
<%= puts "Rendering _search_results.html.erb for #{@opportunities.size} opportunities" %>
<div class="volunteer-container">
<% @opportunities.each do |opportunity| %>
  <div>
    <span class="opportunity-title"><%= opportunity.title %></span>
    <p><strong>Organization: </strong><%= opportunity.organization_name %></p>
    <p><%= opportunity.description %></p>
    <p>Location<strong> | </strong> <%= opportunity.location %></p>
    <button><%= link_to 'Learn More', show_opportunity_path(opportunity) %></button>
<hr>
  </div>
<% end %>
</div>
<div class="aside">
<div class="aside-img">
  <%= image_tag 'holdbox.png', alt: "ladies holding a box" %>
</div>
<div class="aside-spn">
  <span class="spn1">New Ways to</br> Search</span></br></br>
  <span class="spn2">Featured Causes</span></br></br>
  <p class="aside-p1">Highlighted Opportunities:</p>
  <p class="aside-p2">Education Initiatives</p>
  <p class="aside-p2"> Community Health & Wellness</p></br>
  <span class="spn3">Volunteer with your</br> family, co-workers,</br> civic group,& more</span>
</div>
</div>

  

app/views/discover_opportunities/edit.html.erb
<%= render "form", create_opportunity: @create_opportunity %>

app/views/discover_opportunities/search.html.erb
<div class="search-box">
<%= form_tag search_opportunities_path, method: :get, remote: true do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by title or location" %>
  <%= submit_tag "Search", class: "search-button"  %>
<% end %>
</div>
<div id="search-results">
  <%= render partial: 'search_results' %>
</div>

app/views/discover_opportunities/search.js.erb
# $("#search-results").html("<%= j render 'discover_opportunities/search_results' %>");

app/views/discover_opportunities/show.html.erb
<div class="opportunity-cont">
<h1 class="opportunity-title"><%= @create_opportunity.title %></h1>
<p class="opportunity-info"><strong>Organization:</strong> <%= @create_opportunity.organization_name %></p>
<hr>
<p class="opportunity-info"><%= @create_opportunity.description %></p>
<p class="opportunity-info"><strong>Location:</strong> <%= @create_opportunity.location %></p>
<button id="interestedBtn" class="interestedbutton" data-opportunity-id="<%= @create_opportunity.id %>">Interested</button><br><br>



  <%= link_to "🖊️", edit_opportunity_path(@create_opportunity),  class: "edit-button" %>



  <%= link_to "🗑", create_opportunity_path(@create_opportunity), method: :delete, data: { confirm: "Are you sure?"}, class: "delete-button" %>


  <%= link_to "Back", search_opportunities_path, class: "opportunity-buttons" %>

</div>

app/views/home/index.html.erb
<div class="home-container">
<div class="homepage-header">
  <h1>Elevate Impact, <br>Inspire Change</h1>
</div>

<div class="homepage-content">
  <p>Discover tailored volunteer opportunities matching your skills effortlessly. Join a community committed to purposeful impact and positive change.</p>
</div>
</div>

<div class="home-btn">
<button>Get started</button>
</div>

<div class="people-animation">
<%= image_tag("people1.png", alt: "people") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VolunteerConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'home.css' %>
    <%= stylesheet_link_tag 'create_opportunities.css' %>
    <%= stylesheet_link_tag 'search.css' %>
    <%= stylesheet_link_tag 'volunteer.css' %>
    <%= stylesheet_link_tag 'login.css' %>
    <%= stylesheet_link_tag 'signup.css' %>
    <%= stylesheet_link_tag 'volunteer_show.css' %>
    <%= javascript_importmap_tags %>



    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_include_tag 'add_jquery' %>
    <%= javascript_include_tag 'api_button' %>

    
  </head>

  <body>
  <nav>
  <div class="container">
    <div class="logo">
      <%= image_tag("logo.png", alt: "logo") %>
      <span class="logo-text">VolunteerConnect</span>
    </div>
    
    <div class="nav-container">
      <ul class="navbar">
        <li><%= link_to 'Home', root_path, style: "font-size: 17px;" %></li>
        <li><%= link_to 'Volunteers', search_opportunities_path, style: "font-size: 17px;" %></li>
        <li>
          <%= user_signed_in? ? (current_user.organization? ? link_to('Organization', new_create_opportunity_path) : '') : link_to('Log in', new_user_session_path, style: 'font-size: 17px;') %>
        </li>
        <li>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'sign-out' if user_signed_in? %>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>